# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  android: circleci/android@1.0
jobs:
  build:
    working_directory: ~/code
    docker:
      #cicleci image for JAVA version 1.8
      - image: androidsdk/android-30


    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      # Generate apk
      - run: ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/

      # run tests!
      - run: ./gradlew test

