# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  android: circleci/android@1.0
jobs:
  build:
    working_directory: ~/code
    docker:
      #cicleci image for JAVA version 1.8
           - image: circleci/android:api-26-node

    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Set Up Gradle
          command: chmod +x ./gradlew
            - run:
                name: Install Dependencies
                command: ./gradlew dependencies
            - run:
                name: Run Tests
                command: ./gradlew test



workflows:
  build_and_test:
    jobs:
      - build
