version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-jdk  # Use an OpenJDK 17 image
    steps:
      - checkout  # Pull the code from your repository
      - run:
          name: Set Up Gradle
          command: chmod +x ./gradlew
      - run:
          name: Verify Java Version
          command: java -version
      - run:
          name: Run Tests
          command: ./gradlew test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
